name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull manylinux images
      run: |
        for arch in x86_64 aarch64 ppc64le; do
          docker pull quay.io/pypa/manylinux2014_$arch
          docker tag quay.io/pypa/manylinux2014_$arch ghcr.io/spack/manylinux2014:latest-$arch
          docker push ghcr.io/spack/manylinux2014:latest-$arch
        done

        docker manifest create ghcr.io/spack/manylinux2014:example \
          ghcr.io/spack/manylinux2014:latest-x86_64 \
          ghcr.io/spack/manylinux2014:latest-aarch64 \
          ghcr.io/spack/manylinux2014:latest-ppc64le

        docker login ghcr.io -u ${{ secrets.GITHUB_ACTOR }} -p ${{ secrets.GITHUB_TOKEN }}
        docker manifest push ghcr.io/spack/manylinux2014:example